"""
WinoWin Recepcionista — SQLite Database Layer
"""
import json
import logging
from datetime import datetime, timezone, timedelta, date
from pathlib import Path

import aiosqlite

from app.config import config, DATA_DIR

logger = logging.getLogger(__name__)

# ── SQL schema ──────────────────────────────────────────────
SCHEMA = """
CREATE TABLE IF NOT EXISTS messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    wa_message_id TEXT UNIQUE,           -- wamid from WhatsApp
    from_number TEXT NOT NULL,           -- sender phone number
    to_number TEXT,                      -- recipient (business number)
    text TEXT,                           -- message body
    media_type TEXT,                     -- text, image, audio, etc.
    media_url TEXT,                      -- URL to media if present
    timestamp_wa TEXT,                   -- original WhatsApp timestamp
    received_at TEXT NOT NULL DEFAULT (datetime('now')),
    direction TEXT NOT NULL DEFAULT 'incoming',  -- incoming / outgoing
    status TEXT DEFAULT 'received',      -- received, processed, responded, failed
    ai_response TEXT,                    -- response generated by Groq
    ai_model TEXT,                       -- which model generated the response
    ai_tokens_used INTEGER,              -- token usage
    ai_latency_ms INTEGER,              -- latency in ms
    error TEXT,                          -- error message if any
    raw_payload TEXT                     -- full JSON payload from Meta
);

CREATE TABLE IF NOT EXISTS conversations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    from_number TEXT NOT NULL,
    started_at TEXT NOT NULL DEFAULT (datetime('now')),
    last_message_at TEXT NOT NULL DEFAULT (datetime('now')),
    message_count INTEGER DEFAULT 1,
    status TEXT DEFAULT 'active',        -- active, closed, handed_off
    state TEXT DEFAULT 'IDLE',           -- Fase 7: IDLE, ASKING_PRICE, BOOKING, AWAITING_CONFIRMATION, CONFIRMED, COMPLETED, COMPLAINT, HANDOFF
    context_json TEXT DEFAULT '{}',      -- Fase 7: persisted entities (last_service_mentioned, last_date_mentioned, client_name, etc.)
    last_activity TEXT,                  -- Fase 7: last activity timestamp for 24h timeout
    notes TEXT
);

-- Fase 5B: Availability system
CREATE TABLE IF NOT EXISTS services (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    price REAL NOT NULL,
    duration_min INTEGER NOT NULL,
    description TEXT
);

CREATE TABLE IF NOT EXISTS schedule (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT NOT NULL,                  -- YYYY-MM-DD
    time TEXT NOT NULL,                  -- HH:MM
    status TEXT NOT NULL DEFAULT 'free', -- free, booked, blocked
    UNIQUE(date, time)
);

CREATE TABLE IF NOT EXISTS appointments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    service_id INTEGER NOT NULL REFERENCES services(id),
    client_name TEXT NOT NULL DEFAULT '',
    client_phone TEXT NOT NULL,
    date TEXT NOT NULL,                  -- YYYY-MM-DD
    start_time TEXT NOT NULL,            -- HH:MM
    end_time TEXT NOT NULL,              -- HH:MM
    status TEXT NOT NULL DEFAULT 'booked',  -- booked, cancelled, completed
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_messages_from ON messages(from_number);
CREATE INDEX IF NOT EXISTS idx_messages_timestamp ON messages(received_at);
CREATE INDEX IF NOT EXISTS idx_messages_wa_id ON messages(wa_message_id);
CREATE INDEX IF NOT EXISTS idx_conversations_from ON conversations(from_number);
CREATE INDEX IF NOT EXISTS idx_services_category ON services(category);
CREATE INDEX IF NOT EXISTS idx_services_name ON services(name);
CREATE INDEX IF NOT EXISTS idx_schedule_date ON schedule(date);
CREATE INDEX IF NOT EXISTS idx_schedule_status ON schedule(status);
CREATE INDEX IF NOT EXISTS idx_appointments_date ON appointments(date);
CREATE INDEX IF NOT EXISTS idx_appointments_phone ON appointments(client_phone);
"""


async def init_db() -> aiosqlite.Connection:
    """Initialize database: create directory and tables."""
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    db = await aiosqlite.connect(config.database_path)
    db.row_factory = aiosqlite.Row
    await db.executescript(SCHEMA)
    await db.commit()

    # Fase 7: Run migrations for new columns
    await _migrate_conversations_table(db)

    logger.info(f"✅ Database initialized at {config.database_path}")
    return db


async def _migrate_conversations_table(db: aiosqlite.Connection) -> None:
    """Fase 7: Add new columns if they don't exist (SQLite doesn't support ALTER COLUMN well)."""
    try:
        await db.execute("ALTER TABLE conversations ADD COLUMN state TEXT DEFAULT 'IDLE'")
        logger.info("📦 Migration: added conversations.state column")
    except Exception:
        pass  # Column already exists

    try:
        await db.execute("ALTER TABLE conversations ADD COLUMN context_json TEXT DEFAULT '{}'")
        logger.info("📦 Migration: added conversations.context_json column")
    except Exception:
        pass

    try:
        await db.execute("ALTER TABLE conversations ADD COLUMN last_activity TEXT")
        logger.info("📦 Migration: added conversations.last_activity column")
    except Exception:
        pass

    await db.commit()


async def save_incoming_message(
    db: aiosqlite.Connection,
    wa_message_id: str,
    from_number: str,
    text: str | None,
    to_number: str | None = None,
    media_type: str = "text",
    media_url: str | None = None,
    timestamp_wa: str | None = None,
    raw_payload: dict | None = None,
) -> int:
    """Save an incoming WhatsApp message. Returns the row id."""
    now = datetime.now(timezone.utc).isoformat()
    raw_json = json.dumps(raw_payload) if raw_payload else None

    cursor = await db.execute(
        """
        INSERT INTO messages
            (wa_message_id, from_number, to_number, text, media_type, media_url,
             timestamp_wa, received_at, direction, status, raw_payload)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'incoming', 'received', ?)
        ON CONFLICT(wa_message_id) DO NOTHING
        """,
        (wa_message_id, from_number, to_number, text, media_type, media_url,
         timestamp_wa, now, raw_json),
    )
    await db.commit()

    if cursor.lastrowid:
        logger.info(f"💾 Saved message {wa_message_id} from {from_number} (id={cursor.lastrowid})")
        return cursor.lastrowid
    else:
        logger.debug(f"⚠️ Duplicate message {wa_message_id} skipped")
        # Get existing row id
        row = await db.execute(
            "SELECT id FROM messages WHERE wa_message_id = ?", (wa_message_id,)
        )
        existing = await row.fetchone()
        return existing[0] if existing else 0


async def save_ai_response(
    db: aiosqlite.Connection,
    message_id: int,
    ai_response: str,
    ai_model: str,
    ai_tokens_used: int = 0,
    ai_latency_ms: int = 0,
) -> None:
    """Update a message record with the AI-generated response."""
    await db.execute(
        """
        UPDATE messages
        SET ai_response = ?, ai_model = ?, ai_tokens_used = ?, ai_latency_ms = ?,
            status = 'processed'
        WHERE id = ?
        """,
        (ai_response, ai_model, ai_tokens_used, ai_latency_ms, message_id),
    )
    await db.commit()
    logger.info(f"🤖 AI response saved for message {message_id}")


async def update_message_status(
    db: aiosqlite.Connection,
    message_id: int,
    status: str,
    error: str | None = None,
) -> None:
    """Update message status."""
    await db.execute(
        "UPDATE messages SET status = ?, error = ? WHERE id = ?",
        (status, error, message_id),
    )
    await db.commit()


async def update_or_create_conversation(
    db: aiosqlite.Connection,
    from_number: str,
) -> int:
    """Update existing conversation or create a new one. Returns conversation id.
    Fase 7: Checks last_activity — if > 24h, starts fresh conversation.
    """
    now = datetime.now(timezone.utc)
    now_iso = now.isoformat()

    # Try to find active conversation
    cursor = await db.execute(
        "SELECT id, message_count, last_activity FROM conversations "
        "WHERE from_number = ? AND status = 'active'",
        (from_number,),
    )
    row = await cursor.fetchone()

    if row:
        conv_id, count, last_activity = row["id"], row["message_count"], row["last_activity"]

        # Fase 7: If last activity > 24h, close old conversation and start new
        if last_activity:
            try:
                last_dt = datetime.fromisoformat(last_activity)
                if (now - last_dt).total_seconds() > 86400:  # 24h
                    await db.execute(
                        "UPDATE conversations SET status = 'closed' WHERE id = ?",
                        (conv_id,),
                    )
                    await db.commit()
                    logger.info(f"🕐 Conversation {conv_id} auto-closed (>24h inactive)")
                    # Fall through to create new conversation
                    row = None
            except (ValueError, TypeError):
                pass  # Invalid timestamp, just update
        else:
            # No last_activity set yet, treat as active
            pass

    if row:
        conv_id = row["id"]
        count = row["message_count"]
        await db.execute(
            "UPDATE conversations SET last_message_at = ?, last_activity = ?, message_count = ? WHERE id = ?",
            (now_iso, now_iso, count + 1, conv_id),
        )
        await db.commit()
        return conv_id
    else:
        cursor = await db.execute(
            "INSERT INTO conversations (from_number, started_at, last_message_at, last_activity) "
            "VALUES (?, ?, ?, ?)",
            (from_number, now_iso, now_iso, now_iso),
        )
        await db.commit()
        return cursor.lastrowid


async def get_conversation_history(
    db: aiosqlite.Connection,
    from_number: str,
    limit: int = 10,
) -> list[dict]:
    """Get recent conversation history for context."""
    cursor = await db.execute(
        """
        SELECT text, ai_response, direction, received_at
        FROM messages
        WHERE from_number = ?
        ORDER BY received_at DESC
        LIMIT ?
        """,
        (from_number, limit),
    )
    rows = await cursor.fetchall()
    return [dict(row) for row in reversed(rows)]


# ── Fase 7: Conversation State & Context Management ─────────────

async def get_conversation(db: aiosqlite.Connection, from_number: str) -> dict | None:
    """Get the active conversation for a phone number with state and context."""
    cursor = await db.execute(
        "SELECT * FROM conversations WHERE from_number = ? AND status = 'active' "
        "ORDER BY last_message_at DESC LIMIT 1",
        (from_number,),
    )
    row = await cursor.fetchone()
    if not row:
        return None
    conv = dict(row)
    # Parse context_json
    import json as _json
    try:
        conv["context"] = _json.loads(conv.get("context_json", "{}"))
    except (json.JSONDecodeError, TypeError):
        conv["context"] = {}
    return conv


async def update_conversation_state(
    db: aiosqlite.Connection,
    conv_id: int,
    state: str,
) -> None:
    """Update the state of a conversation."""
    await db.execute(
        "UPDATE conversations SET state = ? WHERE id = ?",
        (state, conv_id),
    )
    await db.commit()
    logger.info(f"🔄 Conversation {conv_id} state → {state}")


async def update_conversation_context(
    db: aiosqlite.Connection,
    conv_id: int,
    context: dict,
) -> None:
    """Update the persisted context (entities) for a conversation."""
    import json as _json
    context_json = _json.dumps(context, ensure_ascii=False)
    await db.execute(
        "UPDATE conversations SET context_json = ? WHERE id = ?",
        (context_json, conv_id),
    )
    await db.commit()
    logger.debug(f"📝 Conversation {conv_id} context updated: {context}")


async def close_conversation(
    db: aiosqlite.Connection,
    conv_id: int,
    status: str = "closed",
) -> None:
    """Close a conversation (mark as completed or handed_off)."""
    await db.execute(
        "UPDATE conversations SET status = ?, state = ? WHERE id = ?",
        (status, "COMPLETED" if status == "closed" else "HANDOFF", conv_id),
    )
    await db.commit()
    logger.info(f"🔒 Conversation {conv_id} → {status}")




# ── Services catalog ────────────────────────────────────────
async def search_services(db: aiosqlite.Connection, query: str) -> list[dict]:
    """Search services by name with individual word matching.
    Each word in the query is searched separately with LIKE.
    """
    if not query or not query.strip():
        # Return all services
        cursor = await db.execute(
            """SELECT id, name, category, price, duration_min, description
               FROM services ORDER BY price ASC"""
        )
        rows = await cursor.fetchall()
        return [dict(row) for row in rows]

    # Build individual word searches
    words = query.strip().split()
    conditions = []
    params = []
    for word in words:
        if len(word) >= 2:  # Skip single-character words
            conditions.append("(name LIKE ? OR category LIKE ? OR description LIKE ?)")
            params.extend([f"%{word}%", f"%{word}%", f"%{word}%"])

    if not conditions:
        return []

    where_clause = " AND ".join(conditions)
    cursor = await db.execute(
        f"""SELECT id, name, category, price, duration_min, description
            FROM services
            WHERE {where_clause}
            ORDER BY price ASC
            LIMIT 15""",
        params,
    )
    rows = await cursor.fetchall()
    return [dict(row) for row in rows]


async def get_services_by_category(db: aiosqlite.Connection, category: str) -> list[dict]:
    """Get all services in a category."""
    cursor = await db.execute(
        """
        SELECT id, name, category, price, duration_min, description
        FROM services
        WHERE category LIKE ?
        ORDER BY price ASC
        """,
        (f"%{category}%",),
    )
    rows = await cursor.fetchall()
    return [dict(row) for row in rows]


async def get_all_categories(db: aiosqlite.Connection) -> list[str]:
    """Get all distinct service categories."""
    cursor = await db.execute(
        "SELECT DISTINCT category FROM services ORDER BY category"
    )
    rows = await cursor.fetchall()
    return [row[0] for row in rows]


async def get_stats(db: aiosqlite.Connection) -> dict:
    """Get basic stats for health check."""
    cursor = await db.execute("SELECT COUNT(*) as total FROM messages")
    total_messages = (await cursor.fetchone())[0]

    cursor = await db.execute("SELECT COUNT(*) as total FROM conversations WHERE status = 'active'")
    active_conversations = (await cursor.fetchone())[0]

    cursor = await db.execute(
        "SELECT COUNT(*) as total FROM messages WHERE direction = 'incoming' AND status = 'processed'"
    )
    processed = (await cursor.fetchone())[0]

    return {
        "total_messages": total_messages,
        "active_conversations": active_conversations,
        "processed_messages": processed,
        "database": str(config.database_path),
    }


# ────────────────────────────────────────────────────────────────
# Fase 5B: Availability & Appointments
# ────────────────────────────────────────────────────────────────

# Business hours configuration
BUSINESS_HOURS = {
    0: [(9, 14), (16, 20)],  # Monday: 9:00-14:00, 16:00-20:00
    1: [(9, 14), (16, 20)],  # Tuesday
    2: [(9, 14), (16, 20)],  # Wednesday
    3: [(9, 14), (16, 20)],  # Thursday
    4: [(9, 14), (16, 20)],  # Friday
    5: [(9, 14)],            # Saturday: 9:00-14:00
    6: [],                   # Sunday: closed
}
SLOT_DURATION_MIN = 30


def _time_to_minutes(t: str) -> int:
    """Convert HH:MM string to minutes since midnight."""
    h, m = t.split(":")
    return int(h) * 60 + int(m)


def _minutes_to_time(m: int) -> str:
    """Convert minutes since midnight to HH:MM string."""
    return f"{m // 60:02d}:{m % 60:02d}"


def _slot_end_time(start_time: str, duration_min: int) -> str:
    """Calculate end time from a start time and duration."""
    total = _time_to_minutes(start_time) + duration_min
    return _minutes_to_time(total)


async def generate_slots(db: aiosqlite.Connection, days: int = 30) -> int:
    """Generate time slots for the next N days. Only fills empty slots.
    Returns the number of slots created.
    """
    today = date.today()
    count = 0

    for day_offset in range(days):
        d = today + timedelta(days=day_offset)
        date_str = d.isoformat()
        weekday = d.weekday()  # 0=Monday, 6=Sunday

        slots_for_day = BUSINESS_HOURS.get(weekday, [])
        if not slots_for_day:
            continue  # Sunday or closed day

        # Check if slots already exist for this day
        cursor = await db.execute(
            "SELECT COUNT(*) FROM schedule WHERE date = ?", (date_str,)
        )
        existing = (await cursor.fetchone())[0]
        if existing > 0:
            continue  # Slots already generated for this day

        for (start_h, end_h) in slots_for_day:
            current = start_h * 60
            end = end_h * 60
            while current + SLOT_DURATION_MIN <= end:
                time_str = _minutes_to_time(current)
                await db.execute(
                    "INSERT OR IGNORE INTO schedule (date, time, status) VALUES (?, ?, 'free')",
                    (date_str, time_str),
                )
                count += 1
                current += SLOT_DURATION_MIN

    if count > 0:
        await db.commit()
        logger.info(f"📅 Generated {count} new schedule slots for {days} days")
    else:
        logger.info(f"📅 No new slots needed — slots already exist for the next {days} days")

    return count


async def get_availability(db: aiosqlite.Connection, date_str: str) -> list[dict]:
    """Return all slots (free and booked) for a given date. YYYY-MM-DD."""
    cursor = await db.execute(
        "SELECT id, date, time, status FROM schedule WHERE date = ? ORDER BY time",
        (date_str,),
    )
    rows = await cursor.fetchall()
    return [dict(row) for row in rows]


async def get_available_slots(
    db: aiosqlite.Connection, date_str: str, duration_min: int
) -> list[dict]:
    """Find consecutive free slots that can accommodate a service of duration_min.
    Returns a list of available start times, each with enough consecutive free slots.
    """
    # Get all free slots for the day
    cursor = await db.execute(
        "SELECT time FROM schedule WHERE date = ? AND status = 'free' ORDER BY time",
        (date_str,),
    )
    free_times = [row[0] for row in await cursor.fetchall()]

    if not free_times:
        return []

    # Convert to minutes for easier math
    free_minutes = sorted([_time_to_minutes(t) for t in free_times])
    slots_needed = (duration_min + SLOT_DURATION_MIN - 1) // SLOT_DURATION_MIN

    available_starts = []

    for i, start_min in enumerate(free_minutes):
        # Check if we have enough consecutive slots starting here
        if i + slots_needed > len(free_minutes):
            break

        consecutive = True
        for j in range(1, slots_needed):
            expected = free_minutes[i] + j * SLOT_DURATION_MIN
            if free_minutes[i + j] != expected:
                consecutive = False
                break

        if consecutive:
            end_min = start_min + duration_min
            available_starts.append({
                "date": date_str,
                "start_time": _minutes_to_time(start_min),
                "end_time": _minutes_to_time(end_min),
                "slots_count": slots_needed,
            })

    return available_starts


async def book_appointment(
    db: aiosqlite.Connection,
    service_id: int,
    client_name: str,
    client_phone: str,
    date_str: str,
    start_time: str,
) -> dict | None:
    """Book an appointment: create appointment record + block schedule slots.
    Returns the appointment dict on success, None if slots are not available.
    """
    # Get service duration
    cursor = await db.execute(
        "SELECT id, name, duration_min, price FROM services WHERE id = ?",
        (service_id,),
    )
    service = await cursor.fetchone()
    if not service:
        logger.error(f"❌ Service {service_id} not found")
        return None

    duration = service["duration_min"]
    end_time = _slot_end_time(start_time, duration)
    slots_needed = (duration + SLOT_DURATION_MIN - 1) // SLOT_DURATION_MIN

    # Verify all needed slots are free
    start_min = _time_to_minutes(start_time)
    slot_times = []
    for i in range(slots_needed):
        slot_min = start_min + i * SLOT_DURATION_MIN
        slot_times.append(_minutes_to_time(slot_min))

    for t in slot_times:
        cursor = await db.execute(
            "SELECT status FROM schedule WHERE date = ? AND time = ?",
            (date_str, t),
        )
        row = await cursor.fetchone()
        if not row or row["status"] != "free":
            logger.warning(f"⚠️ Slot {date_str} {t} is not free — cannot book")
            return None

    # Block all slots
    for t in slot_times:
        await db.execute(
            "UPDATE schedule SET status = 'booked' WHERE date = ? AND time = ?",
            (date_str, t),
        )

    # Create appointment
    now = datetime.now(timezone.utc).isoformat()
    cursor = await db.execute(
        """INSERT INTO appointments
           (service_id, client_name, client_phone, date, start_time, end_time, status, created_at)
           VALUES (?, ?, ?, ?, ?, ?, 'booked', ?)""",
        (service_id, client_name, client_phone, date_str, start_time, end_time, now),
    )
    await db.commit()
    appointment_id = cursor.lastrowid

    logger.info(
        f"📅 Appointment #{appointment_id} booked: {service['name']} for {client_name} "
        f"on {date_str} {start_time}-{end_time}"
    )

    return {
        "id": appointment_id,
        "service_id": service_id,
        "service_name": service["name"],
        "service_price": service["price"],
        "client_name": client_name,
        "client_phone": client_phone,
        "date": date_str,
        "start_time": start_time,
        "end_time": end_time,
        "status": "booked",
    }


async def cancel_appointment(db: aiosqlite.Connection, appointment_id: int) -> bool:
    """Cancel an appointment and free its schedule slots.
    Returns True on success, False if not found.
    """
    cursor = await db.execute(
        "SELECT id, date, start_time, service_id FROM appointments WHERE id = ?",
        (appointment_id,),
    )
    appt = await cursor.fetchone()
    if not appt:
        logger.warning(f"⚠️ Appointment #{appointment_id} not found")
        return False

    # Get service duration
    cursor = await db.execute(
        "SELECT duration_min FROM services WHERE id = ?", (appt["service_id"],)
    )
    service = await cursor.fetchone()
    duration = service["duration_min"] if service else 30

    slots_needed = (duration + SLOT_DURATION_MIN - 1) // SLOT_DURATION_MIN
    start_min = _time_to_minutes(appt["start_time"])

    # Free all slots
    for i in range(slots_needed):
        slot_min = start_min + i * SLOT_DURATION_MIN
        t = _minutes_to_time(slot_min)
        await db.execute(
            "UPDATE schedule SET status = 'free' WHERE date = ? AND time = ?",
            (appt["date"], t),
        )

    # Update appointment status
    await db.execute(
        "UPDATE appointments SET status = 'cancelled' WHERE id = ?",
        (appointment_id,),
    )
    await db.commit()
    logger.info(f"📅 Appointment #{appointment_id} cancelled — slots freed")
    return True


async def get_appointments_for_date(
    db: aiosqlite.Connection, date_str: str
) -> list[dict]:
    """Get all booked appointments for a given date."""
    cursor = await db.execute(
        """SELECT a.id, a.service_id, s.name as service_name, a.client_name,
                  a.client_phone, a.date, a.start_time, a.end_time, a.status
           FROM appointments a
           JOIN services s ON a.service_id = s.id
           WHERE a.date = ? AND a.status = 'booked'
           ORDER BY a.start_time""",
        (date_str,),
    )
    rows = await cursor.fetchall()
    return [dict(row) for row in rows]


async def get_available_dates(
    db: aiosqlite.Connection, duration_min: int, limit: int = 7
) -> list[dict]:
    """Find upcoming dates that have at least one available slot for the given duration.
    Returns dates with available slots.
    """
    today = date.today()
    results = []

    for day_offset in range(30):  # search up to 30 days ahead
        d = today + timedelta(days=day_offset)
        date_str = d.isoformat()
        weekday = d.weekday()
        if not BUSINESS_HOURS.get(weekday):
            continue  # closed day

        slots = await get_available_slots(db, date_str, duration_min)
        if slots:
            results.append({
                "date": date_str,
                "weekday": d.strftime("%A"),
                "available_slots_count": len(slots),
                "first_available": slots[0]["start_time"] if slots else None,
            })

        if len(results) >= limit:
            break

    return results
